import { useState } from "react";
import { Badge, Button, Card, Disclaimer, ScreenHeader } from "../components/ui";
import type { TrackedCase } from "../types";
import { advanceStatus, listCases } from "../lib/caseStore";
import { formatJourneyDateTime } from "../lib/riskEngine";

const STATUS_LABELS: Record<TrackedCase["status"], string> = {
  created: "Case created",
  under_review: "Under review",
  next_action: "Next action identified",
  outcome_pending: "Mock outcome pending",
  resolved: "Simulated outcome resolved",
};

export function CaseTracker({
  kase,
  onCaseUpdated,
  onStartOver,
  onHome,
}: {
  kase: TrackedCase;
  onCaseUpdated: (k: TrackedCase) => void;
  onStartOver: () => void;
  onHome: () => void;
}) {
  const [othersOpen, setOthersOpen] = useState(false);
  const [copying, setCopying] = useState(false);
  const [feedback, setFeedback] = useState<"yes" | "no" | null>(() => {
    try {
      return (
        (localStorage.getItem(`tdr-feedback-${kase.caseId}`) as "yes" | "no") ||
        null
      );
    } catch {
      return null;
    }
  });

  const otherCases = listCases().filter((c) => c.caseId !== kase.caseId);
  const currentIdx = kase.timeline.findIndex((s) => !s.done);

  const handleCopy = () => {
    const text = `TDR Sahayak — Case Summary (Prototype)
─────────────────────────
Case ID: ${kase.caseId}
Status: ${STATUS_LABELS[kase.status]}
Scenario: ${kase.decision.scenarioTitle}
Classification: ${kase.decision.classification}
Risk Level: ${kase.decision.riskLevel}
Recommended Action: ${kase.decision.recommendedAction}

Checklist:
${kase.decision.checklist.map((item) => `  ☐ ${item}`).join("\n")}
─────────────────────────
Generated by TDR Sahayak (prototype, not official)`;
    navigator.clipboard.writeText(text);
    setCopying(true);
    setTimeout(() => setCopying(false), 2000);
  };

  const handleFeedback = (val: "yes" | "no") => {
    try {
      localStorage.setItem(`tdr-feedback-${kase.caseId}`, val);
    } catch {}
    setFeedback(val);
  };

  const handleResetFeedback = () => {
    try {
      localStorage.removeItem(`tdr-feedback-${kase.caseId}`);
    } catch {}
    setFeedback(null);
  };

  return (
    <>
      {/* ──────────────────────────────────────────────────────────── */}
      {/* 1. INTERACTIVE SCREEN UI (Hidden when printing)               */}
      {/* ──────────────────────────────────────────────────────────── */}
      <div className="animate-fade-up print:hidden">
        <ScreenHeader
          title="Case tracker"
          subtitle="A local, synthetic record of your mock case."
          onBack={onHome}
        />

        {/* Case ID and Status */}
        <Card className="bg-rail-900 text-white">
          <div className="flex items-start justify-between gap-3">
            <div>
              <p className="text-xs font-bold uppercase tracking-widest text-rail-100">
                Case ID
              </p>
              <p className="mt-1 font-mono text-lg font-bold tracking-wide text-amber-signal">
                {kase.caseId}
              </p>
              <p className="mt-1 text-xs text-rail-100">
                Created {formatJourneyDateTime(kase.createdAt)}
              </p>
            </div>
            <Badge tone={kase.status === "resolved" ? "green" : "amber"}>
              {STATUS_LABELS[kase.status]}
            </Badge>
          </div>
        </Card>

        {/* Progress Timeline */}
        <Card className="mt-4">
          <h2 className="text-base font-bold text-rail-950">Progress</h2>
          <ol className="mt-4">
            {kase.timeline.map((step, i) => {
              const active = i === currentIdx;
              return (
                <li key={step.label} className="flex gap-3">
                  <div className="flex flex-col items-center">
                    <span
                      aria-hidden
                      className={`flex h-7 w-7 items-center justify-center rounded-full text-xs font-bold ${
                        step.done
                          ? "bg-rail-600 text-white"
                          : active
                            ? "bg-amber-signal text-rail-950"
                            : "bg-rail-100 text-rail-700"
                      }`}
                    >
                      {step.done ? "✓" : i + 1}
                    </span>
                    {i < kase.timeline.length - 1 && (
                      <span
                        aria-hidden
                        className={`w-0.5 flex-1 ${step.done ? "bg-rail-600" : "bg-rail-100"}`}
                        style={{ minHeight: 30 }}
                      />
                    )}
                  </div>
                  <div className="pb-7">
                    <p
                      className={`text-sm font-semibold ${step.done ? "text-rail-950" : active ? "text-rail-950" : "text-stone-500"}`}
                    >
                      {step.label}
                    </p>
                    {step.at && (
                      <p className="text-xs text-stone-500">
                        {formatJourneyDateTime(step.at)}
                      </p>
                    )}
                    {active && (
                      <p className="mt-1 text-xs font-medium text-amber-800">
                        In progress in this demo
                      </p>
                    )}
                  </div>
                </li>
              );
            })}
          </ol>

          {kase.status !== "resolved" && (
            <Button
              variant="secondary"
              onClick={() => onCaseUpdated(advanceStatus(kase))}
              className="mt-1 w-full"
            >
              {kase.status === "outcome_pending"
                ? "Simulate outcome resolution (demo)"
                : "Simulate next review step (demo)"}
            </Button>
          )}

          {kase.status === "outcome_pending" && (
            <p className="mt-2 rounded-xl bg-rail-50 px-3.5 py-3 text-xs text-rail-900 border border-rail-100">
              Your mock case is awaiting final simulated determination. Advance once more to simulate the resolved review outcome.
            </p>
          )}

          {kase.status === "resolved" && (
            <div className="mt-2 rounded-xl bg-rail-50 px-3.5 py-3 text-xs text-rail-900 border border-rail-200">
              <span className="font-semibold text-rail-950">Simulated review resolved:</span> This mock case has completed the prototype simulation cycle. (No actual claim was filed or financial refund issued.)
            </div>
          )}
        </Card>

        {/* 4. Resolved-Case Feedback (Only when status is resolved) */}
        {kase.status === "resolved" && (
          <Card className="mt-4 border-amber-200 bg-amber-50/40">
            <div className="flex items-center gap-2">
              <span className="flex h-5 w-5 items-center justify-center rounded-full bg-amber-signal text-rail-950 text-xs font-bold">
                ★
              </span>
              <h2 className="text-sm font-bold text-rail-950">Simulated outcome feedback</h2>
            </div>
            <p className="mt-2 text-sm text-stone-700">
              Was this simulated outcome as expected?
            </p>

            {feedback ? (
              <div className="mt-3 flex items-center justify-between rounded-xl bg-white p-3 border border-stone-200">
                <div>
                  <p className="text-xs text-stone-500">Your feedback:</p>
                  <p className="text-sm font-semibold text-rail-950">
                    {feedback === "yes"
                      ? "✓ Yes — outcome matched expectations"
                      : "✕ No — outcome did not match"}
                  </p>
                </div>
                <button
                  onClick={handleResetFeedback}
                  className="text-xs font-semibold text-stone-500 hover:text-rail-700 underline"
                >
                  Change
                </button>
              </div>
            ) : (
              <div className="mt-3 flex gap-2.5">
                <button
                  onClick={() => handleFeedback("yes")}
                  className="flex-1 rounded-xl bg-rail-900 px-4 py-2 text-sm font-semibold text-white shadow-sm hover:bg-rail-800 active:scale-95 transition"
                >
                  Yes
                </button>
                <button
                  onClick={() => handleFeedback("no")}
                  className="flex-1 rounded-xl border border-stone-300 bg-white px-4 py-2 text-sm font-semibold text-stone-700 shadow-sm hover:bg-stone-50 active:scale-95 transition"
                >
                  No
                </button>
              </div>
            )}
            <p className="mt-2 text-[11px] text-stone-500">
              Saved locally for this case ID. Does not affect real IRCTC records.
            </p>
          </Card>
        )}

        {/* 1. Expected Timeline Section */}
        <Card className="mt-4">
          <div className="flex items-start justify-between gap-2">
            <div>
              <h2 className="text-base font-bold text-rail-950">Expected timeline</h2>
              <p className="mt-0.5 text-xs text-stone-500 italic">
                Illustrative processing journey. Actual processing time may vary.
              </p>
            </div>
            <span className="rounded-full bg-rail-100 px-2.5 py-0.5 text-[11px] font-semibold text-rail-800">
              Illustrative
            </span>
          </div>

          <p className="mt-2.5 text-xs leading-relaxed text-stone-600">
            In an official railway filing, your case moves through three core evaluation stages. Processing duration depends on chart audits, station verification, and banking gateway networks:
          </p>

          <div className="mt-3.5 space-y-2.5">
            <div className="rounded-xl border border-rail-100 bg-stone-50/70 p-3">
              <div className="flex items-center gap-2">
                <span className="flex h-5 w-5 items-center justify-center rounded-full bg-rail-800 text-[11px] font-bold text-white">
                  1
                </span>
                <h3 className="text-sm font-semibold text-rail-950">Verification</h3>
              </div>
              <p className="mt-1 pl-7 text-xs text-stone-600 leading-relaxed">
                Railway commercial officers review train operating logs, chart preparation timestamps, or station/TTE certificates against your claim details.
              </p>
            </div>

            <div className="rounded-xl border border-rail-100 bg-stone-50/70 p-3">
              <div className="flex items-center gap-2">
                <span className="flex h-5 w-5 items-center justify-center rounded-full bg-rail-800 text-[11px] font-bold text-white">
                  2
                </span>
                <h3 className="text-sm font-semibold text-rail-950">Refund calculation</h3>
              </div>
              <p className="mt-1 pl-7 text-xs text-stone-600 leading-relaxed">
                Applicable refund amounts are calculated according to statutory Railway rules (e.g. full fare for cancellation or severe delay, or untravelled distance/class difference).
              </p>
            </div>

            <div className="rounded-xl border border-rail-100 bg-stone-50/70 p-3">
              <div className="flex items-center gap-2">
                <span className="flex h-5 w-5 items-center justify-center rounded-full bg-rail-800 text-[11px] font-bold text-white">
                  3
                </span>
                <h3 className="text-sm font-semibold text-rail-950">Final decision or credit</h3>
              </div>
              <p className="mt-1 pl-7 text-xs text-stone-600 leading-relaxed">
                The formal decision is finalized and communicated. If approved, credits are disbursed through the banking network back to the original payment source.
              </p>
            </div>
          </div>

          <div className="mt-3 rounded-xl border border-amber-200/70 bg-amber-50/60 p-2.5 text-[11px] text-amber-900">
            <span className="font-semibold">Notice:</span> TDR Sahayak does not process claims or guarantee railway settlement timelines.
          </div>
        </Card>

        {/* 2. “If your claim is rejected” Section */}
        <Card className="mt-4">
          <h2 className="text-base font-bold text-rail-950">If your claim is rejected</h2>
          <p className="mt-1 text-xs text-stone-600">
            Official railway refund or TDR claims are typically rejected due to one of these common causes:
          </p>

          <ul className="mt-3 space-y-2 text-xs text-stone-700">
            <li className="flex items-start gap-2">
              <span className="font-bold text-red-500">•</span>
              <div>
                <strong className="text-rail-950">Incorrect or incomplete details:</strong> Discrepancies in PNR number, passenger name, coach/berth, or travel dates.
              </div>
            </li>
            <li className="flex items-start gap-2">
              <span className="font-bold text-red-500">•</span>
              <div>
                <strong className="text-rail-950">Missing information:</strong> Failure to provide required physical evidence, such as a TTE deboarding certificate or Excess Fare Ticket (EFT).
              </div>
            </li>
            <li className="flex items-start gap-2">
              <span className="font-bold text-red-500">•</span>
              <div>
                <strong className="text-rail-950">Unsuitable claim category:</strong> Selecting a TDR reason that conflicts with the actual travel record (e.g., claiming a delay refund after completing the full journey).
              </div>
            </li>
            <li className="flex items-start gap-2">
              <span className="font-bold text-red-500">•</span>
              <div>
                <strong className="text-rail-950">Claim outside the applicable time window:</strong> Filing after the permissible window (e.g. past chart preparation or exceeding 72 hours for en-route disruptions).
              </div>
            </li>
            <li className="flex items-start gap-2">
              <span className="font-bold text-red-500">•</span>
              <div>
                <strong className="text-rail-950">Railway records not matching submitted information:</strong> Train delay or route records logged in the National Train Enquiry System (NTES) differing from your claim.
              </div>
            </li>
          </ul>

          <div className="mt-3.5 rounded-xl border border-rail-200 bg-rail-50/70 p-3">
            <p className="text-xs font-semibold text-rail-950">Official grievance & support channels</p>
            <p className="mt-1 text-xs text-stone-700 leading-relaxed">
              If you believe an official rejection was issued in error, you can escalate through legitimate railway channels:
            </p>
            <ul className="mt-2 space-y-1.5 text-xs text-stone-700">
              <li>• <strong>RailMadad Portal & Mobile App:</strong> Lodge a formal grievance on the official Indian Railways passenger redressal portal or dial <strong>139</strong>.</li>
              <li>• <strong>IRCTC Customer Care:</strong> Email customer support at <strong>etickets@irctc.co.in</strong> or phone <strong>14646 / 0755-6610661</strong> quoting your PNR.</li>
              <li>• <strong>Zonal Railway CCM (Refunds):</strong> Submit a written representation along with original certificates to the Chief Commercial Manager of the concerned railway zone.</li>
            </ul>
            <p className="mt-2 text-[11px] text-stone-500 italic">
              Always verify contact instructions directly on the official IRCTC portal.
            </p>
          </div>
        </Card>

        {/* What Happens Next & Print/Copy Buttons */}
        <Card className="mt-4">
          <h2 className="text-base font-bold text-rail-950">What happens next?</h2>
          <p className="mt-2 text-sm leading-relaxed text-stone-700">
            In a real implementation, this layer could connect to the appropriate
            official process — for example, guiding you to the official refund or
            TDR filing channel with your facts already organised. This prototype
            does not connect to government systems, and no real claim has been or
            will be filed.
          </p>
          <div className="mt-3 rounded-xl bg-rail-50 px-3.5 py-3 mb-3">
            <p className="text-sm font-semibold text-rail-950">Your next action</p>
            <p className="mt-1 text-sm text-stone-700">
              {kase.decision.recommendedAction}
            </p>
          </div>

          <div className="mt-4 flex flex-col gap-2">
            <Button
              variant="secondary"
              onClick={handleCopy}
              className="w-full flex justify-center items-center gap-2"
            >
              {copying ? (
                "✓ Copied!"
              ) : (
                <>
                  <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    <rect x="9" y="9" width="13" height="13" rx="2" ry="2"></rect>
                    <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path>
                  </svg>
                  Copy case summary
                </>
              )}
            </Button>

            {/* 3. Print or Save Case Summary Button */}
            <Button
              variant="secondary"
              onClick={() => window.print()}
              className="w-full flex justify-center items-center gap-2"
            >
              <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <polyline points="6 9 6 2 18 2 18 9"></polyline>
                <path d="M6 18H4a2 2 0 0 1-2-2v-5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2h-2"></path>
                <rect x="6" y="14" width="12" height="8"></rect>
              </svg>
              Print or save case summary
            </Button>
          </div>
        </Card>

        {/* Other Local Mock Cases */}
        {otherCases.length > 0 && (
          <div className="mt-4">
            <button
              onClick={() => setOthersOpen((o) => !o)}
              className="flex w-full items-center justify-between rounded-xl border border-rail-100 bg-white px-4 py-3.5 text-left text-sm font-semibold text-rail-900 hover:bg-rail-50"
            >
              Other mock cases in this browser ({otherCases.length})
              <span aria-hidden>{othersOpen ? "▾" : "▸"}</span>
            </button>
            {othersOpen && (
              <ul className="mt-2 grid gap-2">
                {otherCases.map((c) => (
                  <li
                    key={c.caseId}
                    className="flex items-center justify-between rounded-xl border border-rail-100 bg-white px-4 py-3"
                  >
                    <span className="font-mono text-sm text-rail-950">{c.caseId}</span>
                    <span className="text-xs text-stone-500">
                      {STATUS_LABELS[c.status]}
                    </span>
                  </li>
                ))}
              </ul>
            )}
          </div>
        )}

        {/* Navigation & Home buttons */}
        <div className="mt-6 space-y-3">
          <Button onClick={onStartOver}>Start over</Button>
          <Button variant="ghost" onClick={onHome}>
            Back to home
          </Button>
          <Disclaimer className="text-center" />
        </div>
      </div>

      {/* ──────────────────────────────────────────────────────────── */}
      {/* 2. DEDICATED CLEAN PRINT LAYOUT (Only visible when printing)  */}
      {/* ──────────────────────────────────────────────────────────── */}
      <div className="hidden print:block text-stone-900 text-sm leading-relaxed p-6 max-w-3xl mx-auto">
        {/* Print Header */}
        <div className="border-b-2 border-stone-800 pb-4">
          <div className="flex items-center justify-between">
            <div>
              <h1 className="text-2xl font-black tracking-tight text-stone-900">
                TDR Sahayak
              </h1>
              <p className="text-xs uppercase tracking-wider text-stone-600 font-semibold mt-0.5">
                Railway Disruption Case Summary • Autonomous Passenger Guidance
              </p>
            </div>
            <div className="text-right">
              <span className="inline-block border border-stone-400 bg-stone-100 px-2.5 py-1 text-xs font-mono font-bold">
                SYNTHETIC PROTOTYPE
              </span>
            </div>
          </div>

          <div className="mt-3 grid grid-cols-3 gap-2 text-xs border-t border-stone-200 pt-2 text-stone-700">
            <div>
              <span className="text-stone-500 font-medium">Case ID:</span>{" "}
              <strong className="font-mono text-stone-950">{kase.caseId}</strong>
            </div>
            <div>
              <span className="text-stone-500 font-medium">Date Created:</span>{" "}
              <strong>{formatJourneyDateTime(kase.createdAt)}</strong>
            </div>
            <div>
              <span className="text-stone-500 font-medium">Simulated Status:</span>{" "}
              <strong className="text-stone-950">{STATUS_LABELS[kase.status]}</strong>
            </div>
          </div>
        </div>

        {/* Incident Description */}
        <div className="mt-4 border-b border-stone-200 pb-4">
          <h2 className="text-xs font-bold uppercase tracking-wider text-stone-500">
            Passenger Incident Description
          </h2>
          <p className="mt-1.5 italic text-stone-800 bg-stone-50 p-2.5 border border-stone-200 rounded">
            "{kase.facts.incidentText}"
          </p>
        </div>

        {/* Extracted Facts */}
        <div className="mt-4 border-b border-stone-200 pb-4">
          <h2 className="text-xs font-bold uppercase tracking-wider text-stone-500">
            Structured Facts Extracted
          </h2>
          <div className="mt-2 grid grid-cols-2 gap-x-4 gap-y-1.5 text-xs">
            <div>
              <span className="text-stone-500">Travel Status:</span>{" "}
              <strong>
                {kase.facts.passengerTravelled === true
                  ? "Travelled"
                  : kase.facts.passengerTravelled === false
                    ? "Did not travel"
                    : "Unclear"}
              </strong>
            </div>
            <div>
              <span className="text-stone-500">Boarding Status:</span>{" "}
              <strong>
                {kase.facts.passengerBoarded === true
                  ? "Boarded train"
                  : kase.facts.passengerBoarded === false
                    ? "Could not board"
                    : "Unclear"}
              </strong>
            </div>
            <div>
              <span className="text-stone-500">Journey Completed:</span>{" "}
              <strong>
                {kase.facts.journeyCompleted === true
                  ? "Completed to destination"
                  : kase.facts.journeyCompleted === false
                    ? "Not completed"
                    : "Unclear"}
              </strong>
            </div>
            <div>
              <span className="text-stone-500">Partial Journey Disruption:</span>{" "}
              <strong>
                {kase.facts.partialJourney === true
                  ? "Yes (interrupted en route)"
                  : "No"}
              </strong>
            </div>
            <div>
              <span className="text-stone-500">Train Delay Duration:</span>{" "}
              <strong>
                {kase.facts.delayDuration === "gt6h"
                  ? "6+ hours"
                  : kase.facts.delayDuration === "3to6h"
                    ? "3 to 6 hours"
                    : kase.facts.delayDuration === "lt3h"
                      ? "Under 3 hours"
                      : "Not confirmed"}
              </strong>
            </div>
            <div>
              <span className="text-stone-500">Ticket Cancelled:</span>{" "}
              <strong>
                {kase.facts.cancelledBeforeDeparture === true
                  ? "Yes"
                  : kase.facts.cancelledBeforeDeparture === false
                    ? "No"
                    : "Unclear"}
              </strong>
            </div>
            {kase.facts.disruptionMentioned && (
              <div className="col-span-2">
                <span className="text-stone-500">Disruption Reason:</span>{" "}
                <strong>{kase.facts.disruptionMentioned}</strong>
              </div>
            )}
          </div>
        </div>

        {/* Recommendation & Checklist */}
        <div className="mt-4 border-b border-stone-200 pb-4">
          <h2 className="text-xs font-bold uppercase tracking-wider text-stone-500">
            Deterministic Recommendation
          </h2>
          <p className="mt-1 text-base font-bold text-stone-950">
            {kase.decision.scenarioTitle}
          </p>
          <div className="mt-2 rounded bg-stone-100 p-3 border border-stone-300">
            <p className="text-xs font-bold text-stone-700 uppercase tracking-wide">
              Recommended Next Step:
            </p>
            <p className="mt-1 text-xs font-medium text-stone-950 leading-relaxed">
              {kase.decision.recommendedAction}
            </p>
          </div>
          <p className="mt-2 text-xs text-stone-700 leading-relaxed">
            {kase.decision.explanation}
          </p>

          <div className="mt-3">
            <p className="text-xs font-bold text-stone-900 mb-1.5">Action Checklist:</p>
            <ul className="space-y-1 text-xs text-stone-800">
              {kase.decision.checklist.map((item, idx) => (
                <li key={idx} className="flex items-start gap-2">
                  <span className="font-mono text-stone-400">[ ]</span>
                  <span>{item}</span>
                </li>
              ))}
            </ul>
          </div>
        </div>

        {/* Timing & Risk */}
        <div className="mt-4 border-b border-stone-200 pb-4">
          <h2 className="text-xs font-bold uppercase tracking-wider text-stone-500">
            Timing & Risk Assessment
          </h2>
          <div className="mt-2 grid grid-cols-2 gap-4 text-xs">
            <div>
              <span className="text-stone-500">Assessed Risk Level:</span>{" "}
              <strong className="uppercase">{kase.decision.riskLevel}</strong>
              <p className="mt-0.5 text-stone-600">{kase.decision.riskNote}</p>
            </div>
            <div>
              <span className="text-stone-500">Filing Window:</span>{" "}
              <strong>{kase.deadline.statusLabel}</strong>
              <p className="mt-0.5 text-stone-600">{kase.deadline.statusDetail}</p>
            </div>
          </div>
        </div>

        {/* Expected Timeline (Print view) */}
        <div className="mt-4 border-b border-stone-200 pb-4 text-xs text-stone-700">
          <h2 className="text-xs font-bold uppercase tracking-wider text-stone-500">
            Expected Official Timeline & Rejection Pointers
          </h2>
          <p className="mt-1 italic text-stone-600">
            Illustrative processing journey. Actual processing time may vary.
          </p>
          <div className="mt-2 grid grid-cols-3 gap-2">
            <div className="border border-stone-200 p-2 rounded">
              <strong>1. Verification:</strong> Operating logs and certificates audited.
            </div>
            <div className="border border-stone-200 p-2 rounded">
              <strong>2. Refund calculation:</strong> Amount determined under statutory rules.
            </div>
            <div className="border border-stone-200 p-2 rounded">
              <strong>3. Decision / Credit:</strong> Official decision finalized and disbursed.
            </div>
          </div>
          <p className="mt-2 text-[11px] text-stone-600">
            If rejected: Common causes include PNR mismatch, missing TTE certificate, or filing past deadline. Escalate via RailMadad (139) or IRCTC customer support (etickets@irctc.co.in).
          </p>
        </div>

        {/* Prototype Disclaimer */}
        <div className="mt-4 text-[11px] text-stone-600 bg-stone-100 p-3 border border-stone-300 rounded">
          <p className="font-bold text-stone-800">PROTOTYPE NOTICE / DISCLAIMER:</p>
          <p className="mt-1 leading-normal">
            TDR Sahayak is an educational and hackathon submission for Build What Moves India / Fund My Crazy. It organizes passenger-described incident facts and maps them against Indian Railways refund rules. This tool does NOT connect to Indian Railways, CRIS, or IRCTC official servers. No actual claim has been filed and no financial refund has been issued. Citizens must file claims through official channels (irctc.co.in or RailMadad 139).
          </p>
        </div>
      </div>
    </>
  );
}

