import { useState } from "react";
import { Badge, Button, Card, Disclaimer, ScreenHeader, StepProgress } from "../components/ui";
import type { CaseFacts, DecisionResult, AnalysisResult, DeadlineAssessment, OutcomeFeedback } from "../types";
import { formatJourneyDateTime, toLocalInputValue, defaultJourneyDateTime } from "../lib/riskEngine";
import { saveFeedback } from "../lib/feedbackStore";

const TIMELINE_STEPS = [
  "Journey incident",
  "Recommended action window",
  "Claim preparation",
  "Mock submission",
];

function getIncidentTypeLabel(type: string) {
  switch (type) {
    case "delay_not_travelled": return "Train delayed, did not travel";
    case "could_not_board": return "Could not board";
    case "partial_journey": return "Partial journey (disrupted midway)";
    case "travelled_completed": return "Travelled and completed journey";
    case "travelled_disrupted": return "Travelled but disrupted";
    case "ambiguous": return "Ambiguous / Other";
    default: return type;
  }
}

function getDelayDurationLabel(delay: string) {
  switch (delay) {
    case "gt6h": return "More than 6 hours";
    case "3to6h": return "3 to 6 hours";
    case "lt3h": return "Less than 3 hours";
    case "unsure": return "Unsure / Unconfirmed";
    default: return delay;
  }
}

export function DecisionResultScreen({
  facts,
  decision,
  analysis,
  assessment,
  userCorrectedAnswer,
  onJourneyDateTimeChange,
  onPrepareCase,
  onBack,
}: {
  facts: CaseFacts;
  decision: DecisionResult;
  analysis: AnalysisResult;
  assessment: DeadlineAssessment;
  userCorrectedAnswer?: boolean;
  onJourneyDateTimeChange: (value: string) => void;
  onPrepareCase: () => void;
  onBack: () => void;
}) {
  const [copying, setCopying] = useState(false);
  const [outcome, setOutcome] = useState<OutcomeFeedback["selectedOutcome"]>("completed");
  const [helpful, setHelpful] = useState(true);
  const [outcomeNotes, setOutcomeNotes] = useState("");
  const [feedbackSaved, setFeedbackSaved] = useState(false);

  const isTravelUncertain = facts.passengerTravelled === "unknown";

  const activeStep =
    assessment.status === "outside_window"
      ? 4
      : assessment.status === "window_closing"
        ? 2
        : 1;

  const riskTone =
    assessment.riskLevel === "low"
      ? "green"
      : assessment.riskLevel === "medium"
        ? "amber"
        : "red";

  const handleCopy = () => {
    const text = `TDR Sahayak — Case Summary (Prototype)
─────────────────────────
Scenario: ${decision.scenarioTitle}
Classification: ${decision.classification}
Risk Level: ${decision.riskLevel}
Recommended Action: ${decision.recommendedAction}

Checklist:
${decision.checklist.map((item) => `  ☐ ${item}`).join('\n')}
─────────────────────────
Generated by TDR Sahayak (prototype, not official)`;
    navigator.clipboard.writeText(text);
    setCopying(true);
    setTimeout(() => setCopying(false), 2000);
  };

  return (
    <div className="animate-fade-up">
      {/* Title as requested: "Your recommended next step" */}
      <ScreenHeader
        title="Your recommended next step"
        subtitle={`Scenario ${decision.scenario} · ${decision.scenarioTitle}`}
        onBack={onBack}
        right={
          <Badge tone={riskTone}>
            Timing Risk: {assessment.riskLevel}
          </Badge>
        }
      />
      <StepProgress step={4} />

      {/* Uncertainty warning if travel status could not be determined */}
      {isTravelUncertain && (
        <Card className="mt-4 border-amber-300 bg-amber-soft">
          <div className="flex items-start gap-2.5">
            <span className="mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-amber-signal text-xs font-extrabold text-rail-950">
              !
            </span>
            <div>
              <p className="text-sm font-bold text-amber-950">
                Provisional Recommendation · Travel status unconfirmed
              </p>
              <p className="mt-1 text-xs leading-relaxed text-amber-900">
                Because it is not confirmed whether you travelled on this ticket, this recommendation is tentative. Indian Railways requires confirmation of whether the passenger travelled before processing delay refunds.
              </p>
            </div>
          </div>
        </Card>
      )}

      {/* Primary Recommended Next Step Card */}
      <div className="mt-5 overflow-hidden rounded-2xl bg-rail-900 text-white shadow-md">
        <div className="flex items-center justify-between border-b border-white/10 bg-rail-800/60 px-5 py-3">
          <p className="text-xs font-bold uppercase tracking-widest text-amber-signal">
            Suggested Next Step · Possible Pathway
          </p>
          <span className="text-[11px] font-semibold text-rail-100">
            Scenario {decision.scenario}
          </span>
        </div>
        <div className="px-5 py-5">
          <p className="text-lg font-bold leading-snug">
            {decision.recommendedAction}
          </p>
          <p className="mt-1 text-xs font-medium text-rail-100/80">
            Based on the facts currently provided by the passenger.
          </p>
          <p className="mt-3 text-sm leading-relaxed text-rail-100">
            {decision.explanation}
          </p>
          <div className="mt-4 flex items-center gap-2 rounded-xl bg-white/10 px-3.5 py-3">
            <span
              aria-hidden
              className={`h-2.5 w-2.5 shrink-0 rounded-full ${
                assessment.riskLevel === "low"
                  ? "bg-emerald-400"
                  : assessment.riskLevel === "medium"
                    ? "bg-amber-signal"
                    : "bg-red-400"
              }`}
            />
            <p className="text-sm leading-snug text-rail-100">
              <span className="font-bold text-white">Timing Status: {assessment.statusLabel}.</span>{" "}
              {assessment.statusDetail}
            </p>
          </div>
        </div>
      </div>

      {/* Requirement E: Visible "Why this recommendation?" section */}
      <Card className="mt-4">
        <div className="flex items-center justify-between">
          <h2 className="text-base font-bold text-rail-950">
            Why this recommendation?
          </h2>
          <Badge tone="rail">Auditable Decision Trail</Badge>
        </div>
        <p className="mt-1 text-xs text-stone-600">
          How passenger input was translated into an official procedural step by the deterministic rules engine.
        </p>

        <div className="mt-4 space-y-3 text-xs text-stone-700">
          {/* 1. What the passenger reported */}
          <div className="rounded-xl border border-rail-100 bg-stone-50/70 p-3">
            <p className="font-bold uppercase tracking-wider text-stone-500 mb-1">
              1. What you reported
            </p>
            <p className="italic text-stone-800 leading-relaxed">
              “{facts.incidentText}”
            </p>
          </div>

          {/* 2. Facts extracted & engine verification */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-2.5">
            <div className="rounded-xl bg-rail-50 p-3 border border-rail-100">
              <p className="font-bold text-rail-950 flex items-center gap-1 mb-2">
                <span>🧠</span> 2. Facts Extracted ({analysis.source})
              </p>
              <ul className="space-y-1 text-stone-700">
                <li>• Incident nature: <span className="font-semibold text-rail-950">{getIncidentTypeLabel(facts.incidentType)}</span></li>
                <li>• Travel status: <span className="font-semibold text-rail-950">{facts.passengerTravelled === true ? "Travelled" : facts.passengerTravelled === false ? "Did not travel" : "Unconfirmed"}</span></li>
                <li>• Boarded train: <span className="font-semibold text-rail-950">{facts.passengerBoarded === true ? "Yes" : facts.passengerBoarded === false ? "No" : "Unconfirmed"}</span></li>
                <li>• Journey completed: <span className="font-semibold text-rail-950">{facts.journeyCompleted === true ? "Yes" : facts.journeyCompleted === false ? "No (disrupted midway)" : "Unconfirmed"}</span></li>
                <li>• Partial journey: <span className="font-semibold text-rail-950">{facts.partialJourney === true ? "Yes, part of route" : facts.partialJourney === false ? "No" : "Unconfirmed"}</span></li>
                <li>• Delay duration: <span className="font-semibold text-rail-950">{getDelayDurationLabel(facts.delayDuration)}</span></li>
                <li>• Disruption: <span className="font-semibold text-rail-950">{facts.disruptionMentioned || "None mentioned"}</span></li>
              </ul>
            </div>

          {/* 3. Railway Rule Applied & Official Source */}
          <div className="rounded-xl bg-amber-soft p-3.5 border border-amber-200">
            <div className="flex items-center justify-between mb-2">
              <p className="font-bold text-rail-950 flex items-center gap-1.5">
                <span>⚖️</span> 3. Railway Rule Applied
              </p>
              <a
                href={decision.decisionBasis?.officialSourceUrl || "https://www.operations.irctc.co.in/ctrs/ruleRefund.html"}
                target="_blank"
                rel="noopener noreferrer"
                className="text-[11px] font-bold text-rail-800 underline hover:text-rail-950 flex items-center gap-1"
              >
                <span>Verify official rule</span>
                <span aria-hidden>↗</span>
              </a>
            </div>
            <ul className="space-y-1.5 text-stone-700">
              <li>• Scenario Matched: <span className="font-semibold text-rail-950">Scenario {decision.scenario} ({decision.scenarioTitle})</span></li>
              <li>• Official Reference: <span className="font-semibold text-rail-950">{decision.decisionBasis?.ruleApplied ?? "Gazetted Indian Railways Coaching Refund Rules"}</span></li>
              <li>• Timing Risk Window: <span className="font-semibold capitalize text-rail-950">{assessment.riskLevel} level ({assessment.statusLabel})</span></li>
            </ul>
          </div>
        </div>

        {/* 4. Why this matters */}
          {decision.decisionBasis?.whyThisMatters && (
            <div className="rounded-xl bg-purple-50/70 p-3.5 border border-purple-200">
              <p className="font-bold text-purple-950 flex items-center gap-1.5 mb-1.5">
                <span>💡</span> 4. Why This Matters (Statutory Significance)
              </p>
              <p className="text-stone-700 leading-relaxed">
                {decision.decisionBasis.whyThisMatters}
              </p>
            </div>
          )}

          {/* 5. Deterministic Engine Logic & Counterfactual */}
          {decision.decisionBasis && (
            <div className="rounded-xl bg-blue-50/70 p-3.5 border border-blue-200">
              <p className="font-bold text-blue-950 flex items-center gap-1.5 mb-1.5">
                <span>🔬</span> 5. Deterministic Engine Logic & Counterfactual
              </p>
              <p className="text-stone-700 leading-relaxed mb-1.5">
                <span className="font-semibold text-blue-950">Pivot Fact:</span> {decision.decisionBasis.keyFact}
              </p>
              <p className="text-stone-700 leading-relaxed">
                <span className="font-semibold text-blue-950">Counterfactual (What if this changed?):</span> {decision.decisionBasis.counterfactual}
              </p>
            </div>
          )}

          {/* 6. Required vs Missing Facts */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-2.5">
            <div className="rounded-xl border border-emerald-200 bg-emerald-50/50 p-3">
              <p className="font-bold uppercase tracking-wider text-emerald-950 mb-1.5">
                Required Facts & Documents
              </p>
              <ul className="space-y-1 text-emerald-900">
                {(decision.requiredFacts ?? ["Confirmed travel status", "Disruption proof"]).map((fact) => (
                  <li key={fact} className="flex items-center gap-1.5">
                    <span aria-hidden>✓</span> {fact}
                  </li>
                ))}
              </ul>
            </div>

            <div className="rounded-xl border border-stone-200 bg-white p-3">
              <p className="font-bold uppercase tracking-wider text-stone-600 mb-1.5">
                Missing Information & Dependencies
              </p>
              {decision.missingInformation.length > 0 ? (
                <ul className="space-y-1 text-amber-900">
                  {decision.missingInformation.map((m) => (
                    <li key={m} className="flex items-center gap-1.5 font-medium">
                      <span aria-hidden>⚠</span> {m}
                    </li>
                  ))}
                </ul>
              ) : (
                <p className="text-emerald-800 font-medium flex items-center gap-1">
                  <span>✓</span> All critical facts required to determine this next step were provided.
                </p>
              )}
            </div>
          </div>

          {/* 7. What to do if this doesn't work (Fallback Action) */}
          <div className="rounded-xl border border-stone-300 bg-stone-100/80 p-3 text-stone-700">
            <p className="font-bold text-stone-900 flex items-center gap-1.5 mb-1">
              <span>🛡️</span> What to do if this doesn't work (Escalation Pathway)
            </p>
            <p className="text-xs leading-relaxed">
              {decision.decisionBasis?.fallbackAction || "If online TDR or counter claim is disputed, escalate directly through Indian Railways' RailMadad grievance portal (railmadad.indianrailways.gov.in) or call 139 with your PNR."}
            </p>
          </div>
        </div>
      </Card>

      {/* Requirement A: Timing & Deadline Information (Merged from DeadlineRisk) */}
      <Card className="mt-4">
        <div className="flex items-center justify-between">
          <div>
            <p className="text-xs font-bold uppercase tracking-widest text-stone-500">
              Timing Horizon
            </p>
            <h2 className="mt-0.5 text-base font-bold text-rail-950">
              Claim window & statutory deadline
            </h2>
          </div>
          <Badge tone={riskTone}>{assessment.statusLabel}</Badge>
        </div>
        <p className="mt-2 text-sm leading-relaxed text-stone-700">
          {assessment.statusDetail}
        </p>

        {/* Claim journey visual timeline */}
        <div className="mt-4 pt-3 border-t border-rail-100">
          <p className="text-xs font-semibold text-stone-500 mb-3">Claim journey progression:</p>
          <ol className="space-y-0">
            {TIMELINE_STEPS.map((label, i) => {
              const done = i < activeStep - 1;
              const active = i === activeStep - 1;
              return (
                <li key={label} className="flex gap-3">
                  <div className="flex flex-col items-center">
                    <span
                      aria-hidden
                      className={`flex h-6 w-6 items-center justify-center rounded-full text-xs font-bold ${
                        done
                          ? "bg-rail-600 text-white"
                          : active
                            ? "bg-amber-signal text-rail-950"
                            : "bg-rail-100 text-rail-700"
                      }`}
                    >
                      {done ? "✓" : i + 1}
                    </span>
                    {i < TIMELINE_STEPS.length - 1 && (
                      <span
                        aria-hidden
                        className={`w-0.5 flex-1 ${done ? "bg-rail-600" : "bg-rail-100"}`}
                        style={{ minHeight: 22 }}
                      />
                    )}
                  </div>
                  <div className="pb-4">
                    <p
                      className={`text-xs font-semibold ${
                        active ? "text-rail-950 font-bold" : done ? "text-rail-800" : "text-stone-500"
                      }`}
                    >
                      {label}
                      {active && (
                        <span className="ml-2 rounded-full bg-amber-soft px-2 py-0.5 text-[9px] font-extrabold uppercase text-amber-900 border border-amber-300">
                          Current Stage
                        </span>
                      )}
                    </p>
                  </div>
                </li>
              );
            })}
          </ol>
        </div>

        {/* Scheduled journey date/time selector */}
        <div className="mt-2 rounded-xl bg-rail-50/60 p-3.5 border border-rail-100">
          <label htmlFor="journey-dt" className="block text-xs font-bold text-rail-950">
            Journey departure date & time:
          </label>
          <input
            id="journey-dt"
            type="datetime-local"
            value={toLocalInputValue(new Date(facts.journeyDateTime))}
            max={toLocalInputValue(new Date())}
            onChange={(e) => {
              const v = e.target.value;
              onJourneyDateTimeChange(
                v ? new Date(v).toISOString() : defaultJourneyDateTime(),
              );
            }}
            className="mt-2 w-full rounded-lg border border-rail-200 bg-white px-3 py-2 text-sm text-ink focus:border-rail-600 focus:outline-none"
          />
          <p className="mt-1.5 text-[11px] text-stone-500">
            Incident set to: <span className="font-semibold text-stone-700">{formatJourneyDateTime(facts.journeyDateTime)}</span>
            {assessment.elapsedNote && ` · about ${assessment.elapsedNote} ago`}
          </p>
        </div>
      </Card>

      {/* Action Checklist */}
      <Card className="mt-4">
        <h2 className="text-base font-bold text-rail-950">
          Action checklist for this claim
        </h2>
        <p className="mt-0.5 text-xs text-stone-600">
          Follow these exact steps to prevent your claim from being rejected:
        </p>
        <ul className="mt-3 space-y-2.5">
          {decision.checklist.map((item) => (
            <li key={item} className="flex items-start gap-3">
              <span
                aria-hidden
                className="mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded border-2 border-rail-600/40 text-xs font-bold text-rail-700"
              >
                ✓
              </span>
              <span className="text-sm leading-snug text-stone-800">{item}</span>
            </li>
          ))}
        </ul>
      </Card>

      {/* Copy Case Summary */}
      <div className="mt-4">
        <Button
          variant="secondary"
          onClick={handleCopy}
          className="w-full flex justify-center items-center gap-2"
        >
          {copying ? "✓ Copied!" : (
            <>
              <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <rect x="9" y="9" width="13" height="13" rx="2" ry="2"></rect>
                <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path>
              </svg>
              Copy case summary
            </>
          )}
        </Button>
      </div>

      {/* What happened next? Prototype Feedback Form */}
      <Card className="mt-4 border-rail-200 bg-stone-50/70">
        <div className="flex items-center justify-between">
          <h2 className="text-base font-bold text-rail-950 flex items-center gap-1.5">
            <span>🗳️</span> What happened next? (Optional outcome feedback)
          </h2>
          <Badge tone="amber">Evaluation Signal</Badge>
        </div>
        <p className="mt-1 text-xs text-stone-600 leading-relaxed">
          Did you already file this claim or experience an outcome? Sharing what happened helps evaluate advice accuracy.
        </p>

        {feedbackSaved ? (
          <div className="mt-3 rounded-xl bg-emerald-50 p-3.5 border border-emerald-200 text-xs text-emerald-900">
            <p className="font-bold flex items-center gap-1">
              <span>✓</span> Feedback recorded locally in this session!
            </p>
            <p className="mt-1 text-emerald-800">
              Aggregated statistics and community reports are viewable in the <strong>Prototype Insights</strong> screen.
            </p>
          </div>
        ) : (
          <form
            onSubmit={(e) => {
              e.preventDefault();
              saveFeedback({
                caseId: facts.ticketNumber || facts.pnrNumber || `case-${Date.now()}`,
                scenario: decision.scenario,
                scenarioTitle: decision.scenarioTitle,
                recommendedAction: decision.recommendedAction,
                selectedOutcome: outcome,
                recommendedActionHelpful: helpful,
                textFeedback: outcomeNotes.trim() || undefined,
                userCorrectedInitialAnswer: userCorrectedAnswer ?? false,
              });
              setFeedbackSaved(true);
            }}
            className="mt-3 space-y-3 text-xs"
          >
            <div>
              <label htmlFor="outcome-select" className="block font-bold text-rail-950 mb-1">
                What happened next?
              </label>
              <select
                id="outcome-select"
                value={outcome}
                onChange={(e) => setOutcome(e.target.value as OutcomeFeedback["selectedOutcome"])}
                className="w-full rounded-lg border border-rail-200 bg-white px-3 py-2 text-xs text-ink focus:border-rail-600 focus:outline-none"
              >
                <option value="completed">I completed the recommended action</option>
                <option value="need_help">I need more help</option>
                <option value="could_not_complete">I could not complete the action</option>
                <option value="different_action">I chose a different action</option>
                <option value="other">Something else</option>
              </select>
            </div>

            <div className="flex items-center gap-2">
              <input
                id="helpful-check"
                type="checkbox"
                checked={helpful}
                onChange={(e) => setHelpful(e.target.checked)}
                className="h-4 w-4 rounded border-rail-300 text-rail-700 focus:ring-rail-500"
              />
              <label htmlFor="helpful-check" className="font-medium text-stone-700">
                Was this recommendation helpful in understanding the relevant rules?
              </label>
            </div>

            <div>
              <label htmlFor="outcome-notes" className="block font-medium text-stone-700 mb-1">
                Tell us more (optional):
              </label>
              <textarea
                id="outcome-notes"
                rows={2}
                placeholder="What happened after you selected this option?"
                value={outcomeNotes}
                onChange={(e) => setOutcomeNotes(e.target.value)}
                className="w-full rounded-lg border border-rail-200 bg-white px-3 py-1.5 text-xs text-ink focus:border-rail-600 focus:outline-none"
              />
            </div>

            <div className="flex items-center justify-between pt-1">
              <p className="text-[11px] text-stone-500 italic">
                Stored locally in browser storage (prototype evaluation).
              </p>
              <Button type="submit" variant="secondary" className="px-3 py-1.5 text-xs">
                Save outcome feedback
              </Button>
            </div>
          </form>
        )}
      </Card>

      {/* Primary CTA: Button to create a mock claim */}
      <div className="mt-5 space-y-3">
        <Button onClick={onPrepareCase}>
          Create mock claim →
        </Button>
        <Disclaimer className="text-center" />
      </div>
    </div>
  );
}
