import { useState } from "react";
import { Badge, Button, Card, Disclaimer, ScreenHeader, StepProgress } from "../components/ui";
import type { CaseFacts, DecisionResult, AnalysisResult, DeadlineAssessment } from "../types";
import { formatJourneyDateTime, toLocalInputValue, defaultJourneyDateTime } from "../lib/riskEngine";

const TIMELINE_STEPS = [
  "Journey incident",
  "Recommended action window",
  "Claim preparation",
  "Mock submission",
];

function getIncidentTypeLabel(type: string) {
  switch (type) {
    case "delay_not_travelled": return "Train delayed, did not travel";
    case "could_not_board": return "Could not board";
    case "partial_journey": return "Partial journey (disrupted midway)";
    case "travelled_completed": return "Travelled and completed journey";
    case "travelled_disrupted": return "Travelled but disrupted";
    case "ambiguous": return "Ambiguous / Other";
    default: return type;
  }
}

function getDelayDurationLabel(delay: string) {
  switch (delay) {
    case "gt6h": return "More than 6 hours";
    case "3to6h": return "3 to 6 hours";
    case "lt3h": return "Less than 3 hours";
    case "unsure": return "Unsure / Unconfirmed";
    default: return delay;
  }
}

export function DecisionResultScreen({
  facts,
  decision,
  analysis,
  assessment,
  onJourneyDateTimeChange,
  onPrepareCase,
  onBack,
}: {
  facts: CaseFacts;
  decision: DecisionResult;
  analysis: AnalysisResult;
  assessment: DeadlineAssessment;
  onJourneyDateTimeChange: (value: string) => void;
  onPrepareCase: () => void;
  onBack: () => void;
}) {
  const [copying, setCopying] = useState(false);

  const isTravelUncertain = facts.passengerTravelled === "unknown";

  const activeStep =
    assessment.status === "outside_window"
      ? 4
      : assessment.status === "window_closing"
        ? 2
        : 1;

  const riskTone =
    assessment.riskLevel === "low"
      ? "green"
      : assessment.riskLevel === "medium"
        ? "amber"
        : "red";

  const handleCopy = () => {
    const text = `TDR Sahayak — Case Summary (Prototype)
─────────────────────────
Scenario: ${decision.scenarioTitle}
Classification: ${decision.classification}
Risk Level: ${decision.riskLevel}
Recommended Action: ${decision.recommendedAction}

Checklist:
${decision.checklist.map((item) => `  ☐ ${item}`).join('\n')}
─────────────────────────
Generated by TDR Sahayak (prototype, not official)`;
    navigator.clipboard.writeText(text);
    setCopying(true);
    setTimeout(() => setCopying(false), 2000);
  };

  return (
    <div className="animate-fade-up">
      {/* Title as requested: "Your recommended next step" */}
      <ScreenHeader
        title="Your recommended next step"
        subtitle={`Scenario ${decision.scenario} · ${decision.scenarioTitle}`}
        onBack={onBack}
        right={
          <Badge tone={riskTone}>
            Timing Risk: {assessment.riskLevel}
          </Badge>
        }
      />
      <StepProgress step={4} />

      {/* Uncertainty warning if travel status could not be determined */}
      {isTravelUncertain && (
        <Card className="mt-4 border-amber-300 bg-amber-soft">
          <div className="flex items-start gap-2.5">
            <span className="mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-amber-signal text-xs font-extrabold text-rail-950">
              !
            </span>
            <div>
              <p className="text-sm font-bold text-amber-950">
                Provisional Recommendation · Travel status unconfirmed
              </p>
              <p className="mt-1 text-xs leading-relaxed text-amber-900">
                Because it is not confirmed whether you travelled on this ticket, this recommendation is tentative. Indian Railways requires confirmation of whether the passenger travelled before processing delay refunds.
              </p>
            </div>
          </div>
        </Card>
      )}

      {/* Primary Recommended Next Step Card */}
      <div className="mt-5 overflow-hidden rounded-2xl bg-rail-900 text-white shadow-md">
        <div className="flex items-center justify-between border-b border-white/10 bg-rail-800/60 px-5 py-3">
          <p className="text-xs font-bold uppercase tracking-widest text-amber-signal">
            Suggested Next Step · Possible Pathway
          </p>
          <span className="text-[11px] font-semibold text-rail-100">
            Scenario {decision.scenario}
          </span>
        </div>
        <div className="px-5 py-5">
          <p className="text-lg font-bold leading-snug">
            {decision.recommendedAction}
          </p>
          <p className="mt-1 text-xs font-medium text-rail-100/80">
            Based on the facts currently provided by the passenger.
          </p>
          <p className="mt-3 text-sm leading-relaxed text-rail-100">
            {decision.explanation}
          </p>
          <div className="mt-4 flex items-center gap-2 rounded-xl bg-white/10 px-3.5 py-3">
            <span
              aria-hidden
              className={`h-2.5 w-2.5 shrink-0 rounded-full ${
                assessment.riskLevel === "low"
                  ? "bg-emerald-400"
                  : assessment.riskLevel === "medium"
                    ? "bg-amber-signal"
                    : "bg-red-400"
              }`}
            />
            <p className="text-sm leading-snug text-rail-100">
              <span className="font-bold text-white">Timing Status: {assessment.statusLabel}.</span>{" "}
              {assessment.statusDetail}
            </p>
          </div>
        </div>
      </div>

      {/* Requirement E: Visible "Why this recommendation?" section */}
      <Card className="mt-4">
        <div className="flex items-center justify-between">
          <h2 className="text-base font-bold text-rail-950">
            Why this recommendation?
          </h2>
          <Badge tone="rail">Auditable Decision Trail</Badge>
        </div>
        <p className="mt-1 text-xs text-stone-600">
          How passenger input was translated into an official procedural step by the deterministic rules engine.
        </p>

        <div className="mt-4 space-y-3 text-xs text-stone-700">
          {/* 1. What the passenger reported */}
          <div className="rounded-xl border border-rail-100 bg-stone-50/70 p-3">
            <p className="font-bold uppercase tracking-wider text-stone-500 mb-1">
              1. What you reported
            </p>
            <p className="italic text-stone-800 leading-relaxed">
              “{facts.incidentText}”
            </p>
          </div>

          {/* 2. Facts extracted & engine verification */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-2.5">
            <div className="rounded-xl bg-rail-50 p-3 border border-rail-100">
              <p className="font-bold text-rail-950 flex items-center gap-1 mb-2">
                <span>🧠</span> 2. Facts Extracted ({analysis.source})
              </p>
              <ul className="space-y-1 text-stone-700">
                <li>• Incident nature: <span className="font-semibold text-rail-950">{getIncidentTypeLabel(facts.incidentType)}</span></li>
                <li>• Travel status: <span className="font-semibold text-rail-950">{facts.passengerTravelled === true ? "Travelled" : facts.passengerTravelled === false ? "Did not travel" : "Unconfirmed"}</span></li>
                <li>• Boarded train: <span className="font-semibold text-rail-950">{facts.passengerBoarded === true ? "Yes" : facts.passengerBoarded === false ? "No" : "Unconfirmed"}</span></li>
                <li>• Journey completed: <span className="font-semibold text-rail-950">{facts.journeyCompleted === true ? "Yes" : facts.journeyCompleted === false ? "No (disrupted midway)" : "Unconfirmed"}</span></li>
                <li>• Partial journey: <span className="font-semibold text-rail-950">{facts.partialJourney === true ? "Yes, part of route" : facts.partialJourney === false ? "No" : "Unconfirmed"}</span></li>
                <li>• Delay duration: <span className="font-semibold text-rail-950">{getDelayDurationLabel(facts.delayDuration)}</span></li>
                <li>• Disruption: <span className="font-semibold text-rail-950">{facts.disruptionMentioned || "None mentioned"}</span></li>
              </ul>
            </div>

            <div className="rounded-xl bg-amber-soft p-3 border border-amber-200">
              <p className="font-bold text-rail-950 flex items-center gap-1 mb-2">
                <span>⚖️</span> 3. Railway Rule Applied
              </p>
              <ul className="space-y-1 text-stone-700">
                <li>• Reference: <span className="font-semibold text-rail-950">Based on explicit decision rules & confirmed facts</span></li>
                <li>• Matched: <span className="font-semibold text-rail-950">Scenario {decision.scenario} ({decision.scenarioTitle})</span></li>
                <li>• Evaluation: <span className="font-semibold text-rail-950">Produced by explicit deterministic rules (AI structures description only)</span></li>
                <li>• Timing risk: <span className="font-semibold capitalize text-rail-950">{assessment.riskLevel} level</span></li>
              </ul>
            </div>
          </div>

          {/* 4. Why the selected scenario matched */}
          <div className="rounded-xl bg-rail-50/50 p-3 border border-rail-100">
            <p className="font-bold uppercase tracking-wider text-rail-900 mb-1">
              4. Scenario match rationale
            </p>
            <p className="text-stone-700 leading-relaxed">
              {decision.classification}
            </p>
          </div>

          {/* 5. What information is still missing */}
          <div className="rounded-xl border border-stone-200 bg-white p-3">
            <p className="font-bold uppercase tracking-wider text-stone-600 mb-1">
              5. Missing information & dependencies
            </p>
            {decision.missingInformation.length > 0 ? (
              <ul className="mt-1 space-y-1">
                {decision.missingInformation.map((m) => (
                  <li key={m} className="flex items-center gap-1.5 text-amber-900 font-medium">
                    <span aria-hidden>⚠</span> {m}
                  </li>
                ))}
              </ul>
            ) : (
              <p className="text-emerald-800 font-medium flex items-center gap-1">
                <span>✓</span> All critical facts required to determine this next step were provided.
              </p>
            )}
          </div>
        </div>
      </Card>

      {/* Requirement A: Timing & Deadline Information (Merged from DeadlineRisk) */}
      <Card className="mt-4">
        <div className="flex items-center justify-between">
          <div>
            <p className="text-xs font-bold uppercase tracking-widest text-stone-500">
              Timing Horizon
            </p>
            <h2 className="mt-0.5 text-base font-bold text-rail-950">
              Claim window & statutory deadline
            </h2>
          </div>
          <Badge tone={riskTone}>{assessment.statusLabel}</Badge>
        </div>
        <p className="mt-2 text-sm leading-relaxed text-stone-700">
          {assessment.statusDetail}
        </p>

        {/* Claim journey visual timeline */}
        <div className="mt-4 pt-3 border-t border-rail-100">
          <p className="text-xs font-semibold text-stone-500 mb-3">Claim journey progression:</p>
          <ol className="space-y-0">
            {TIMELINE_STEPS.map((label, i) => {
              const done = i < activeStep - 1;
              const active = i === activeStep - 1;
              return (
                <li key={label} className="flex gap-3">
                  <div className="flex flex-col items-center">
                    <span
                      aria-hidden
                      className={`flex h-6 w-6 items-center justify-center rounded-full text-xs font-bold ${
                        done
                          ? "bg-rail-600 text-white"
                          : active
                            ? "bg-amber-signal text-rail-950"
                            : "bg-rail-100 text-rail-700"
                      }`}
                    >
                      {done ? "✓" : i + 1}
                    </span>
                    {i < TIMELINE_STEPS.length - 1 && (
                      <span
                        aria-hidden
                        className={`w-0.5 flex-1 ${done ? "bg-rail-600" : "bg-rail-100"}`}
                        style={{ minHeight: 22 }}
                      />
                    )}
                  </div>
                  <div className="pb-4">
                    <p
                      className={`text-xs font-semibold ${
                        active ? "text-rail-950 font-bold" : done ? "text-rail-800" : "text-stone-500"
                      }`}
                    >
                      {label}
                      {active && (
                        <span className="ml-2 rounded-full bg-amber-soft px-2 py-0.5 text-[9px] font-extrabold uppercase text-amber-900 border border-amber-300">
                          Current Stage
                        </span>
                      )}
                    </p>
                  </div>
                </li>
              );
            })}
          </ol>
        </div>

        {/* Scheduled journey date/time selector */}
        <div className="mt-2 rounded-xl bg-rail-50/60 p-3.5 border border-rail-100">
          <label htmlFor="journey-dt" className="block text-xs font-bold text-rail-950">
            Journey departure date & time:
          </label>
          <input
            id="journey-dt"
            type="datetime-local"
            value={toLocalInputValue(new Date(facts.journeyDateTime))}
            max={toLocalInputValue(new Date())}
            onChange={(e) => {
              const v = e.target.value;
              onJourneyDateTimeChange(
                v ? new Date(v).toISOString() : defaultJourneyDateTime(),
              );
            }}
            className="mt-2 w-full rounded-lg border border-rail-200 bg-white px-3 py-2 text-sm text-ink focus:border-rail-600 focus:outline-none"
          />
          <p className="mt-1.5 text-[11px] text-stone-500">
            Incident set to: <span className="font-semibold text-stone-700">{formatJourneyDateTime(facts.journeyDateTime)}</span>
            {assessment.elapsedNote && ` · about ${assessment.elapsedNote} ago`}
          </p>
        </div>
      </Card>

      {/* Action Checklist */}
      <Card className="mt-4">
        <h2 className="text-base font-bold text-rail-950">
          Action checklist for this claim
        </h2>
        <p className="mt-0.5 text-xs text-stone-600">
          Follow these exact steps to prevent your claim from being rejected:
        </p>
        <ul className="mt-3 space-y-2.5">
          {decision.checklist.map((item) => (
            <li key={item} className="flex items-start gap-3">
              <span
                aria-hidden
                className="mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded border-2 border-rail-600/40 text-xs font-bold text-rail-700"
              >
                ✓
              </span>
              <span className="text-sm leading-snug text-stone-800">{item}</span>
            </li>
          ))}
        </ul>
      </Card>

      {/* Copy Case Summary */}
      <div className="mt-4">
        <Button
          variant="secondary"
          onClick={handleCopy}
          className="w-full flex justify-center items-center gap-2"
        >
          {copying ? "✓ Copied!" : (
            <>
              <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <rect x="9" y="9" width="13" height="13" rx="2" ry="2"></rect>
                <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path>
              </svg>
              Copy case summary
            </>
          )}
        </Button>
      </div>

      {/* Primary CTA: Button to prepare a mock case (Requirement A) */}
      <div className="mt-5 space-y-3">
        <Button onClick={onPrepareCase}>
          Prepare mock case →
        </Button>
        <Disclaimer className="text-center" />
      </div>
    </div>
  );
}
